package com.example.browser

import android.net.Uri
import java.net.URLEncoder

enum class SearchEngine(val displayName: String, val searchUrl: String) {
    GOOGLE("Google", "https://www.google.com/search?q="),
    DUCKDUCKGO("DuckDuckGo", "https://duckduckgo.com/?q="),
    BING("Bing", "https://www.bing.com/search?q="),
    BRAVE("Brave Search", "https://search.brave.com/search?q=")
}

enum class AppThemeMode(val displayName: String) {
    SYSTEM("System Default"),
    LIGHT("Light"),
    DARK("Dark"),
    AMOLED("AMOLED Black")
}

enum class NewTabStyle(val displayName: String) {
    PRODUCTIVITY("Dashboard"),
    MINIMALIST("Zen Minimal")
}

enum class DownloadProvider(val displayName: String, val description: String) {
    BUILT_IN("Built-in Manager", "Standard system download manager"),
    EXTERNAL_APP("External / Ask Every Time", "Open 1DM, ADM, IDM, or system app chooser")
}

data class QuickShortcutItem(
    val id: String,
    val title: String,
    val url: String,
    val isAutoGenerated: Boolean = false
)

enum class HttpsMode {
    PREFER_HTTPS,
    HTTPS_ONLY,
    NORMAL
}

enum class ActiveSheet {
    NONE,
    TABS,
    PROFILES,
    BOOKMARKS,
    HISTORY,
    DOWNLOADS,
    PRIVACY_SHIELD,
    SETTINGS,
    CLEAR_DATA,
    NEW_PROFILE_DIALOG,
    EDIT_BOOKMARK_DIALOG
}

data class ActiveTabState(
    val id: String,
    val profileId: String,
    val url: String = "",
    val title: String = "New Tab",
    val faviconUrl: String? = null,
    val progress: Int = 0,
    val isLoading: Boolean = false,
    val canGoBack: Boolean = false,
    val canGoForward: Boolean = false,
    val blockedCount: Int = 0,
    val isSecure: Boolean = true,
    val isPrivate: Boolean = false,
    val isDesktopMode: Boolean = false,
    val searchMatchCount: Int = 0,
    val searchMatchCurrent: Int = 0
)

object UrlUtils {
    private val URL_REGEX = Regex("^(https?://)?[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+(:[0-9]+)?(/.*)?$")
    private val IP_REGEX = Regex("^(https?://)?[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}(:[0-9]+)?(/.*)?$")

    fun parseInputToUrl(input: String, searchEngine: SearchEngine = SearchEngine.GOOGLE): String {
        val trimmed = input.trim()
        if (trimmed.isBlank()) return ""

        if (trimmed.startsWith("http://", ignoreCase = true) || 
            trimmed.startsWith("https://", ignoreCase = true) ||
            trimmed.startsWith("file://", ignoreCase = true) ||
            trimmed.startsWith("about:", ignoreCase = true) ||
            trimmed.startsWith("data:", ignoreCase = true)) {
            return trimmed
        }

        // Check if user entered localhost
        if (trimmed.startsWith("localhost", ignoreCase = true)) {
            return "http://$trimmed"
        }

        // If it looks like a domain or IP (e.g. example.com or 192.168.1.1)
        if (trimmed.contains(".") && !trimmed.contains(" ") && (URL_REGEX.matches(trimmed) || IP_REGEX.matches(trimmed))) {
            return "https://$trimmed"
        }

        // Otherwise perform search with the selected search engine
        return searchEngine.searchUrl + URLEncoder.encode(trimmed, "UTF-8")
    }

    fun extractDomain(url: String): String {
        return try {
            val uri = Uri.parse(url)
            uri.host ?: url
        } catch (e: Exception) {
            url
        }
    }

    fun isHttps(url: String): Boolean {
        return url.startsWith("https://", ignoreCase = true)
    }
}
